### ISSUE TITLE
Icons on top row

### ISSUE THREAD

**Issue by kyleconrad** [AnthelI/Playhub#2]
Is there a guide to set up filters so the source icons show up correctly along the top row (as shown in the screenshots)? I've set up Filter Presets based on source and the name matches the icon names in the theme files, but it's just showing them as text filters at the top of the screen. Wondering if I'm setting up the filters wrong or how best to get it working, as I'd prefer to have the platform icons vs text.

**Comment by AnthelI** [comment]
Hi, filters are handled in the folders "Icons", you should only have to rename the folder "RenameTo'Filters'" to "Filters", and any filters matching with the name of the pictures should get displayed on the main menu as an image.

**Comment by kyleconrad** [comment]
Oh perfect - do y'all have an icon for Playhub that I can use as well? I didn't see an image for that in there. 

Edit to add: oops dang I totally missed it was in there! Thanks again for the help.
