### ISSUE TITLE
Awesome theme but...

### ISSUE THREAD

**Issue by fredystar200** [AnthelI/Playhub#3]
Can you give us all the settings for this theme please ? to make it look like the screenshots... And the font too.
Thanks.

**Comment by AnthelI** [comment]
Hi ! Have you replicate/seen the settings in the README.md ?
For the font you can find it here: source/Fonts, you may have to set it in playnite settings (not to sure/can’t check)

**Comment by fredystar200** [comment]
Yeah Did it. Okay thanks I will try with the Fonts
